2024-11-25 17:07:58,640 - main.py[line:22] - ERROR: Error executing Scrapy command: Command '['scrapy', 'crawl', 'search']' returned non-zero exit status 1.
2024-11-25 17:07:58,651 - main.py[line:24] - ERROR: Error in nlp: object of type 'NoneType' has no len()
2024-11-25 17:07:58,652 - main.py[line:85] - INFO: 情绪分析未成功完成
2024-11-25 18:05:15,777 - main.py[line:22] - ERROR: Error executing Scrapy command: Command '['scrapy', 'crawl', 'search']' returned non-zero exit status 1.
2024-11-25 18:05:15,812 - __init__.py[line:113] - DEBUG: Building prefix dict from the default dictionary ...
2024-11-25 18:05:16,396 - __init__.py[line:146] - DEBUG: Dumping model to file cache C:\Users\DoubleT\AppData\Local\Temp\jieba.cache
2024-11-25 18:05:16,458 - __init__.py[line:164] - DEBUG: Loading model cost 0.647 seconds.
2024-11-25 18:05:16,459 - __init__.py[line:166] - DEBUG: Prefix dict has been built successfully.
2024-11-25 18:06:23,863 - main.py[line:22] - ERROR: Error executing Scrapy command: Command '['scrapy', 'crawl', 'search']' returned non-zero exit status 1.
2024-11-25 18:06:23,885 - __init__.py[line:113] - DEBUG: Building prefix dict from the default dictionary ...
2024-11-25 18:06:23,886 - __init__.py[line:132] - DEBUG: Loading model from cache C:\Users\DoubleT\AppData\Local\Temp\jieba.cache
2024-11-25 18:06:24,500 - __init__.py[line:164] - DEBUG: Loading model cost 0.614 seconds.
2024-11-25 18:06:24,501 - __init__.py[line:166] - DEBUG: Prefix dict has been built successfully.
2024-11-25 18:19:59,350 - __init__.py[line:113] - DEBUG: Building prefix dict from the default dictionary ...
2024-11-25 18:19:59,351 - __init__.py[line:132] - DEBUG: Loading model from cache C:\Users\DoubleT\AppData\Local\Temp\jieba.cache
2024-11-25 18:19:59,956 - __init__.py[line:164] - DEBUG: Loading model cost 0.605 seconds.
2024-11-25 18:19:59,956 - __init__.py[line:166] - DEBUG: Prefix dict has been built successfully.
2024-11-25 18:21:25,396 - main.py[line:62] - INFO: Emotion analysis completed successfully
2024-11-25 19:14:53,587 - __init__.py[line:113] - DEBUG: Building prefix dict from the default dictionary ...
2024-11-25 19:14:53,589 - __init__.py[line:132] - DEBUG: Loading model from cache C:\Users\DoubleT\AppData\Local\Temp\jieba.cache
2024-11-25 19:14:54,292 - __init__.py[line:164] - DEBUG: Loading model cost 0.703 seconds.
2024-11-25 19:14:54,293 - __init__.py[line:166] - DEBUG: Prefix dict has been built successfully.
2024-11-25 19:16:01,025 - main.py[line:62] - INFO: Emotion analysis completed successfully
2024-11-25 20:26:42,045 - __init__.py[line:113] - DEBUG: Building prefix dict from the default dictionary ...
2024-11-25 20:26:42,048 - __init__.py[line:132] - DEBUG: Loading model from cache C:\Users\DoubleT\AppData\Local\Temp\jieba.cache
2024-11-25 20:26:42,781 - __init__.py[line:164] - DEBUG: Loading model cost 0.734 seconds.
2024-11-25 20:26:42,782 - __init__.py[line:166] - DEBUG: Prefix dict has been built successfully.
2024-11-25 20:45:18,452 - __init__.py[line:113] - DEBUG: Building prefix dict from the default dictionary ...
2024-11-25 20:45:18,454 - __init__.py[line:132] - DEBUG: Loading model from cache C:\Users\DoubleT\AppData\Local\Temp\jieba.cache
2024-11-25 20:45:19,341 - __init__.py[line:164] - DEBUG: Loading model cost 0.889 seconds.
2024-11-25 20:45:19,341 - __init__.py[line:166] - DEBUG: Prefix dict has been built successfully.
2024-11-25 20:50:56,311 - __init__.py[line:113] - DEBUG: Building prefix dict from the default dictionary ...
2024-11-25 20:50:56,312 - __init__.py[line:132] - DEBUG: Loading model from cache C:\Users\DoubleT\AppData\Local\Temp\jieba.cache
2024-11-25 20:50:56,988 - __init__.py[line:164] - DEBUG: Loading model cost 0.676 seconds.
2024-11-25 20:50:56,990 - __init__.py[line:166] - DEBUG: Prefix dict has been built successfully.
2024-11-25 21:41:48,659 - __init__.py[line:113] - DEBUG: Building prefix dict from the default dictionary ...
2024-11-25 21:41:48,659 - __init__.py[line:132] - DEBUG: Loading model from cache C:\Users\DoubleT\AppData\Local\Temp\jieba.cache
2024-11-25 21:41:49,407 - __init__.py[line:164] - DEBUG: Loading model cost 0.749 seconds.
2024-11-25 21:41:49,408 - __init__.py[line:166] - DEBUG: Prefix dict has been built successfully.
2024-11-25 21:43:03,535 - __init__.py[line:113] - DEBUG: Building prefix dict from the default dictionary ...
2024-11-25 21:43:03,536 - __init__.py[line:132] - DEBUG: Loading model from cache C:\Users\DoubleT\AppData\Local\Temp\jieba.cache
2024-11-25 21:43:04,261 - __init__.py[line:164] - DEBUG: Loading model cost 0.725 seconds.
2024-11-25 21:43:04,261 - __init__.py[line:166] - DEBUG: Prefix dict has been built successfully.
2024-11-25 21:48:22,264 - __init__.py[line:113] - DEBUG: Building prefix dict from the default dictionary ...
2024-11-25 21:48:22,265 - __init__.py[line:132] - DEBUG: Loading model from cache C:\Users\DoubleT\AppData\Local\Temp\jieba.cache
2024-11-25 21:48:22,931 - __init__.py[line:164] - DEBUG: Loading model cost 0.666 seconds.
2024-11-25 21:48:22,932 - __init__.py[line:166] - DEBUG: Prefix dict has been built successfully.
2024-11-25 22:51:17,770 - __init__.py[line:113] - DEBUG: Building prefix dict from the default dictionary ...
2024-11-25 22:51:17,773 - __init__.py[line:132] - DEBUG: Loading model from cache C:\Users\DoubleT\AppData\Local\Temp\jieba.cache
2024-11-25 22:51:18,408 - __init__.py[line:164] - DEBUG: Loading model cost 0.636 seconds.
2024-11-25 22:51:18,409 - __init__.py[line:166] - DEBUG: Prefix dict has been built successfully.
2024-11-26 00:11:58,685 - main.py[line:44] - INFO: 已删除文件：data_visualization\all_words.csv
2024-11-26 00:11:58,691 - main.py[line:44] - INFO: 已删除文件：data_visualization\predicted_results.csv
2024-11-26 00:11:58,695 - main.py[line:44] - INFO: 已删除文件：data_visualization\positive_words.csv
2024-11-26 00:11:58,699 - main.py[line:44] - INFO: 已删除文件：data_visualization\negative_words.csv
2024-11-26 00:11:58,703 - main.py[line:44] - INFO: 已删除文件：model\processed_data.csv
2024-11-26 00:11:58,708 - main.py[line:44] - INFO: 已删除文件：weibo_crawler\weibo_data.csv
2024-11-26 00:11:58,711 - main.py[line:44] - INFO: 已删除文件：static\wordclouds\pie_chart.png
2024-11-26 00:11:58,714 - main.py[line:44] - INFO: 已删除文件：static\wordclouds\wordcloud_all.png
2024-11-26 00:11:58,717 - main.py[line:44] - INFO: 已删除文件：static\wordclouds\wordcloud_positive.png
2024-11-26 00:11:58,720 - main.py[line:44] - INFO: 已删除文件：static\wordclouds\wordcloud_negative.png
2024-11-26 10:19:15,663 - main.py[line:36] - ERROR: 文件路径不存在：data_visualization\all_words.csv
2024-11-26 10:19:15,663 - main.py[line:36] - ERROR: 文件路径不存在：data_visualization\all_words.csv
2024-11-26 10:19:15,663 - main.py[line:36] - ERROR: 文件路径不存在：data_visualization\predicted_results.csv
2024-11-26 10:19:15,663 - main.py[line:36] - ERROR: 文件路径不存在：data_visualization\predicted_results.csv
2024-11-26 10:19:15,663 - main.py[line:36] - ERROR: 文件路径不存在：data_visualization\positive_words.csv
2024-11-26 10:19:15,663 - main.py[line:36] - ERROR: 文件路径不存在：data_visualization\positive_words.csv
2024-11-26 10:19:15,663 - main.py[line:36] - ERROR: 文件路径不存在：data_visualization\negative_words.csv
2024-11-26 10:19:15,679 - main.py[line:36] - ERROR: 文件路径不存在：data_visualization\negative_words.csv
2024-11-26 10:19:15,679 - main.py[line:36] - ERROR: 文件路径不存在：model\processed_data.csv
2024-11-26 10:19:15,680 - main.py[line:36] - ERROR: 文件路径不存在：model\processed_data.csv
2024-11-26 10:19:15,680 - main.py[line:44] - INFO: 已删除文件：weibo_crawler\weibo_data.csv
2024-11-26 10:19:15,680 - main.py[line:36] - ERROR: 文件路径不存在：weibo_crawler\weibo_data.csv
2024-11-26 10:19:15,680 - main.py[line:36] - ERROR: 文件路径不存在：static\wordclouds\pie_chart.png
2024-11-26 10:19:15,680 - main.py[line:36] - ERROR: 文件路径不存在：static\wordclouds\pie_chart.png
2024-11-26 10:19:15,680 - main.py[line:36] - ERROR: 文件路径不存在：static\wordclouds\wordcloud_all.png
2024-11-26 10:19:15,680 - main.py[line:36] - ERROR: 文件路径不存在：static\wordclouds\wordcloud_all.png
2024-11-26 10:19:15,680 - main.py[line:36] - ERROR: 文件路径不存在：static\wordclouds\wordcloud_positive.png
2024-11-26 10:19:15,680 - main.py[line:36] - ERROR: 文件路径不存在：static\wordclouds\wordcloud_positive.png
2024-11-26 10:19:15,680 - main.py[line:36] - ERROR: 文件路径不存在：static\wordclouds\wordcloud_negative.png
2024-11-26 10:19:15,680 - main.py[line:36] - ERROR: 文件路径不存在：static\wordclouds\wordcloud_negative.png
2024-11-26 10:19:15,893 - _internal.py[line:97] - INFO:  * Detected change in 'E:\\github_repositories\\Emotion-Analysis-Project\\Emotion-Analysis\\weibo_crawler\\weibo_crawler\\settings.py', reloading
2024-11-26 10:25:22,394 - main.py[line:36] - ERROR: 文件路径不存在：data_visualization\all_words.csv
2024-11-26 10:25:22,395 - main.py[line:36] - ERROR: 文件路径不存在：data_visualization\predicted_results.csv
2024-11-26 10:25:22,395 - main.py[line:36] - ERROR: 文件路径不存在：data_visualization\positive_words.csv
2024-11-26 10:25:22,396 - main.py[line:36] - ERROR: 文件路径不存在：data_visualization\negative_words.csv
2024-11-26 10:25:22,396 - main.py[line:36] - ERROR: 文件路径不存在：model\processed_data.csv
2024-11-26 10:25:22,397 - main.py[line:36] - ERROR: 文件路径不存在：weibo_crawler\weibo_data.csv
2024-11-26 10:25:22,397 - main.py[line:36] - ERROR: 文件路径不存在：static\wordclouds\pie_chart.png
2024-11-26 10:25:22,398 - main.py[line:36] - ERROR: 文件路径不存在：static\wordclouds\wordcloud_all.png
